### ISSUE TITLE
Component failed to become ready, forcing ready status.

### ISSUE THREAD

**Issue by mrblonde77** [nachocinalli/adapt-graphicCompare#1]
### Expected Behaviour
After updating the framework and authoring tool version from 
adapt_authoring" from "0.10.5" > "0.11.1."
"adapt_framework" from ": "5.22.4"  >"5.31.9."
the component should work as expected.

### Actual Behaviour
After updating to the current framework and authoring tool version, the component is no longer set to ready.
It failed to become ready -> forcing ready Status.
But the element then also does not appear in the preview.

### Steps to Reproduce
Update to the current versions (see below) and add the graphic Compare Component to a course and click on preview.

### Error Message Console
`TypeError: can't convert null to object
    applySafariLabelClickBlur https:.../preview/644a6f9092ff13054ca3f3a0/647735f3f71d8b1130f481de/adapt/js/adapt.min.js:1
    Backbone 4
    createElement https:.../preview/644a6f9092ff13054ca3f3a0/647735f3f71d8b1130f481de/adapt/js/adapt.min.js:1
[react-dom.production.min.js:141:274](https:.../preview/644a6f9092ff13054ca3f3a0/647735f3f71d8b1130f481de/libraries/react-dom.production.min.js)

Uncaught (in promise) TypeError: can't convert null to object
    applySafariLabelClickBlur https:.../preview/644a6f9092ff13054ca3f3a0/647735f3f71d8b1130f481de/adapt/js/adapt.min.js:1
    Backbone 4
    createElement https:.../preview/644a6f9092ff13054ca3f3a0/647735f3f71d8b1130f481de/adapt/js/adapt.min.js:1
[adapt.min.js:1:177918](https:.../preview/644a6f9092ff13054ca3f3a0/647735f3f71d8b1130f481de/adapt/js/adapt.min.js)

**ERROR: View 647735f3f71d8b1130f481e1 (article), 647ef24e6ebbee04dc16efda (block), 647ef2536ebbee04dc16efe1 (graphicCompare) failed to become ready, forcing ready status.`**

### Versions
Authoring Tool Version: 0.11.1
Framework Version: 5.31.9
Node.js Version: 14.19.0
Operating System: Windows 11

**Comment by nachocinalli** [comment]
Hi Martin, I updated the component, can you try it again?

**Comment by mrblonde77** [comment]
Hi Ignacio, it works now again as exepted! Thanks for the quick reply!
Best Martin
