### ISSUE TITLE
Enhancement to add Bottom Text

### ISSUE THREAD

**Issue by fosterc1** [nachocinalli/adapt-graphicCompare#2]
Hello

Would it be possible to enhance this plugin to add Bottom Text so we can add text under the images similar to the attached?

Thanks
![2023-07-11_10-20-53](https://github.com/nachocinalli/adapt-graphicCompare/assets/29701150/b9b3d26e-c385-48d3-8bc1-a8bffdc7a118)

**Comment by nachocinalli** [comment]
Hello Caleb, adding text below a component is something that happens very frequently. I believe it should be a functionality of the framework itself ([there's a discussion about it](https://github.com/adaptlearning/adapt-contrib-mcq/issues/196)). Currently, in my projects, I use the [adapt-extra](https://github.com/nachocinalli/adapt-extra) extension that allows me to add text and also 'items' (title, body, _graphic). Could you try that extension? If it doesn't work for you, I can add a 'bodyAfter' or 'bottomText' property to this component. It's a simple thing to do.

**Comment by fosterc1** [comment]
Hello Nacho

Thanks for this, Extra works fine for this.

Thanks again
